@startuml OAuth2 Server Flow Diagram
skinparam backgroundColor #FFFFFF
'skinparam handwritten true

skinparam DefaultFontName "맑은 고딕"
skinparam DefaultFontSize 12

skinparam SequenceTitleFontSize 24



title OAuth2 Server Flow Diagram

'participant Alice
entity "Resource Owner" as owner
entity "Client" as client
control "Authorization Server" as server
control "Resource Server" as resource
'actor
'entity "OAuth2 Server" as qrserver
'boundary "Client" as client
'database "OAuth2 Database" as db
'collections Collections

== Authorization Code Grant Type ==
    autonumber 101
    client->server: 권한부여 코드 요청
    owner<--server: 로그인 페이지 응답
    owner->server: 로그인
    note right
        response_type=code
        client_id, client_secret 를 사용하여
        권한 부여 코드 생성
    end note
    client<--server: 권한 부여 코드 응답
    client->server: 권한부여 코드를 전달하여 Access Token 요청
    note right
        response_type=authorization_code
        client_id, client_secret 를 사용하여
        Access Token 생성
    end note
    client<--server: Access Token 응답(옵션 : Refresh Token)
    loop
        client->resource: Access Token을 사용하여 API 호출
        client<--resource: 요청한 데이터 응답
    end


== Implicit Grant ==
    autonumber 201
    client->server: 권한부여 코드 요청
    owner<--server: 로그인 페이지 응답
    owner->server: 로그인
    note right
        response_type=token
        client_id, client_secret 를 사용하여
        Access Token 생성
    end note
    client<--server: Access Token 응답
    client->server: Access Token 검증 요청
    client<--server: Access Token 검증 결과 응답
    loop
        client->resource: Access Token을 사용하여 API 호출
        client<--resource: 요청한 데이터 응답
    end


== Resource Owner Password Credentials Grant ==
    autonumber 301
    owner->client: Authenticate Credentials 위임
    client->server: Authenticate Credentials 을 통해 Access Token 요청
    owner<-server: 로그인 페이지 응답
    owner->server: 로그인
    note right
        response_type=password
        client_id, client_secret, username, password 를 사용하여
        Access Token 생성
    end note
    client<--server: Access Token 응답(옵션 : Refresh Token)
    loop
        client->resource: Access Token을 사용하여 API 호출
        client<--resource: 요청한 데이터 응답
    end


== Client Credentials Grant Type ==
    autonumber 401
    owner->server: Access Token 요청
    note right
        response_type=client_credentials
        client_id, client_secret 를 사용하여
        권한 부여 코드 생성
    end note
    owner<--server: Access Token 응답
    loop
        owner->resource: Access Token을 사용하여 API 호출
        owner<--resource: 요청한 데이터 응답
    end

@enduml